/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 uranus.glb
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/uranus-9c6478f4885d4a0c874d4b63226ac5e0
Title: Uranus
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/uranus.glb')
  return (
    <group {...props} dispose={null} ref={props.innerRef}>
      <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} scale={1.74} />
      <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials['Scene_-_Root']} scale={2.38} />
      <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials['Scene_-_Root']} scale={2.57} />
      <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials['Scene_-_Root']} scale={2.76} />
    </group>
  )
}

useGLTF.preload('/uranus.glb')
